# 3 - Tipos e Conversão de tipos
O Numpy suporta uma variedade de tipos muito maior do que o Python.

Existem 5 tipos básicos numéricos
- Booleans (bool)
- Integers (int)
- Unsigned Intergers (uint)
- Floating Points (float)
- Complex

Complementarmente, a célula abaixo mostra um quadro comparativos com uma maior quantidade de tipos do Numpy.

![datatypes.png](attachment:datatypes.png)

In [ ]:
import numpy as np

In [ ]:
x = np.float32(1.0)
x

1.0

**Comentário 01:** `x` recebe o valor do argumento de `.float32` convertido na faixa de valores do tipo de dado `float32`.

In [ ]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

**Comentário 02:** A lista `[1,2,3]` tem seus valores convertidos para o tipo de dado `ìnt`. O valor retornado é atribuído a `y`.

In [ ]:
z = np.arange(3, dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

**Comentário 03:** `z` recebe um array contendo uma sequência de 3 valores do intervalo de valores do tipo `uint8` partindo do seu primeio valor, no caso o número zero, espaçando de maneira uniforme até chegar ao terceiro valor.

In [ ]:
np.array([1, 2, 3], dtype='f')

array([1., 2., 3.], dtype=float32)

**Comentário 04:** Cria um numpy array a partir da lista `[1, 2, 3]` com os valores do tipo `float32`.

## Convertendo tipos de arrays

Para convertermos arrays Numpy, basta utilizarmos o método astype().

In [ ]:
z.astype(float)

array([0., 1., 2.])

**Comentário 05:** O método `astype()` retorna o array convertido para o tipo especificado.

In [ ]:
np.int8(z)

array([0, 1, 2], dtype=int8)

**Comentário 06**: Na célula acima, `np.int8(z)` está retornando o array `z` convertido para o tipo de dado `int8`

Para verificarmos o tipo de um array Numpy, basta verificarmos o seu atributo dtype.

In [ ]:
z.dtype

dtype('uint8')

**Comentário 07:** Note que nenhum dos métodos de conversão de array's mostrados acima alterou o tipo do array original.